server:
  port: 8081
spring:
  application:
    name: microservices-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF8&useSSL=false
  jpa:
    show-sql: true # 是否打印sql语句
    generate-ddl: true # 是否自动建表
    database: mysql # jpa连接的数据库类型
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
